// Code generated by MockGen. DO NOT EDIT.
// Source: microservice/internal/app/drivers/rest (interfaces: JSONSchemaValidator)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockJSONSchemaValidator is a mock of JSONSchemaValidator interface
type MockJSONSchemaValidator struct {
	ctrl     *gomock.Controller
	recorder *MockJSONSchemaValidatorMockRecorder
}

// MockJSONSchemaValidatorMockRecorder is the mock recorder for MockJSONSchemaValidator
type MockJSONSchemaValidatorMockRecorder struct {
	mock *MockJSONSchemaValidator
}

// NewMockJSONSchemaValidator creates a new mock instance
func NewMockJSONSchemaValidator(ctrl *gomock.Controller) *MockJSONSchemaValidator {
	mock := &MockJSONSchemaValidator{ctrl: ctrl}
	mock.recorder = &MockJSONSchemaValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJSONSchemaValidator) EXPECT() *MockJSONSchemaValidatorMockRecorder {
	return m.recorder
}

// SetSchemaFromBytes mocks base method
func (m *MockJSONSchemaValidator) SetSchemaFromBytes(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSchemaFromBytes", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSchemaFromBytes indicates an expected call of SetSchemaFromBytes
func (mr *MockJSONSchemaValidatorMockRecorder) SetSchemaFromBytes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSchemaFromBytes", reflect.TypeOf((*MockJSONSchemaValidator)(nil).SetSchemaFromBytes), arg0, arg1)
}

// ValidateSchemaFromBytes mocks base method
func (m *MockJSONSchemaValidator) ValidateSchemaFromBytes(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSchemaFromBytes", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSchemaFromBytes indicates an expected call of ValidateSchemaFromBytes
func (mr *MockJSONSchemaValidatorMockRecorder) ValidateSchemaFromBytes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSchemaFromBytes", reflect.TypeOf((*MockJSONSchemaValidator)(nil).ValidateSchemaFromBytes), arg0, arg1)
}
